name: CI
on: [push]

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn']
      - name: Run install
      - run: yarn install --frozen-lockfile # optional, --immutable
      - name: Test the app
      - run: yarn test
      - name: Run lint
      - run: yarn lint
      - name: Build production
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

